-- MySQL Script generated by MySQL Workbench
-- Mon May 18 15:05:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema riskindicator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema riskindicator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `riskindicator` DEFAULT CHARACTER SET utf8mb3 ;
USE `riskindicator` ;

-- -----------------------------------------------------
-- Table `riskindicator`.`reviewer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`reviewer` (
  `reviewer_id` INT NOT NULL AUTO_INCREMENT,
  `reviewer_name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reviewer_id`),
  UNIQUE INDEX `reviewer_name` (`reviewer_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`audit_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(50) NULL DEFAULT NULL,
  `record_id` INT NULL DEFAULT NULL,
  `action_type` VARCHAR(20) NULL DEFAULT NULL,
  `changed_by` INT NULL DEFAULT NULL,
  `change_date` DATETIME NULL DEFAULT NULL,
  `old_value` TEXT NULL DEFAULT NULL,
  `new_value` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_auditlog_reviewer` (`changed_by` ASC) VISIBLE,
  CONSTRAINT `fk_auditlog_reviewer`
    FOREIGN KEY (`changed_by`)
    REFERENCES `riskindicator`.`reviewer` (`reviewer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(100) NOT NULL,
  `client_type` VARCHAR(50) NULL DEFAULT NULL,
  `industry` VARCHAR(50) NULL DEFAULT NULL,
  `risk_rating` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_name` (`client_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`department` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE INDEX `department_name` (`department_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`payment_method` (
  `payment_method_id` INT NOT NULL AUTO_INCREMENT,
  `method_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`payment_method_id`),
  UNIQUE INDEX `method_name` (`method_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`review_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`review_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`status_id`),
  UNIQUE INDEX `status_name` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`vendor` (
  `vendor_id` INT NOT NULL AUTO_INCREMENT,
  `vendor_name` VARCHAR(45) NOT NULL,
  `vendor_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vendor_id`),
  UNIQUE INDEX `vendor_name` (`vendor_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATE NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `vendor_id` INT NOT NULL,
  `department_id` INT NULL DEFAULT NULL,
  `client_id` INT NULL DEFAULT NULL,
  `payment_method_id` INT NULL DEFAULT NULL,
  `risk_score` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_date` (`transaction_date` ASC, `amount` ASC, `vendor_id` ASC, `department_id` ASC) VISIBLE,
  INDEX `fk_transaction_vendor_idx` (`vendor_id` ASC) VISIBLE,
  INDEX `fk_transaction_department` (`department_id` ASC) VISIBLE,
  INDEX `fk_transaction_client` (`client_id` ASC) VISIBLE,
  INDEX `fk_transaction_payment` (`payment_method_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `riskindicator`.`client` (`client_id`),
  CONSTRAINT `fk_transaction_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `riskindicator`.`department` (`department_id`),
  CONSTRAINT `fk_transaction_payment`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `riskindicator`.`payment_method` (`payment_method_id`),
  CONSTRAINT `fk_transaction_vendor`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `riskindicator`.`vendor` (`vendor_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 146
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `review_date` DATE NOT NULL,
  `transaction_id` INT NOT NULL,
  `reviewer_id` INT NOT NULL,
  `status_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_review_transaction1_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `fk_review_reviewer1_idx` (`reviewer_id` ASC) VISIBLE,
  INDEX `fk_review_status` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_reviewer1`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `riskindicator`.`reviewer` (`reviewer_id`),
  CONSTRAINT `fk_review_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `riskindicator`.`review_status` (`status_id`),
  CONSTRAINT `fk_review_transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `riskindicator`.`transaction` (`transaction_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`risk_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`risk_type` (
  `risk_type_id` INT NOT NULL AUTO_INCREMENT,
  `risk_description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`risk_type_id`),
  UNIQUE INDEX `risk_description` (`risk_description` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `riskindicator`.`risk_type_has_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riskindicator`.`risk_type_has_transaction` (
  `risk_type_id` INT NOT NULL,
  `transaction_id` INT NOT NULL,
  PRIMARY KEY (`risk_type_id`, `transaction_id`),
  INDEX `fk_risk_type_has_transaction_transaction1_idx` (`transaction_id` ASC) VISIBLE,
  INDEX `fk_risk_type_has_transaction_risk_type1_idx` (`risk_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_risk_type_has_transaction_risk_type1`
    FOREIGN KEY (`risk_type_id`)
    REFERENCES `riskindicator`.`risk_type` (`risk_type_id`),
  CONSTRAINT `fk_risk_type_has_transaction_transaction1`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `riskindicator`.`transaction` (`transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
